### PR TITLE
feat: Allow extensions to compile under top_builddir

### LINKED ISSUE #76: [Enhancement]: Allow extensions to compile under top_builddir
### Contact Details

_No response_

### What this feature/enhancement tries to solve?

As part of the work on the release package, it is intended to deliver extensions as part of the contrib directory under the engine source code, using the `top_builddir` instead PGXS.

### If want to provide us a more details about how to implement.

Adding a conditional when doing the include of the PGXS.

### Version

babelfishpg_tsql (Default)

### Relevant documentation

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by 3manuek**
Signed-off-by: 3manuek <emanuel@ongres.com>

### Description

Allow building the Babelfish extensions by copying them into the `/contrib` directory of Postgres source code, in addition to supporting PGXS. Add a simple test of non-PGXS builds.
 
### Issues Resolved

#76 

### Check List
- [x] Commits are signed per the DCO using --signoff 

By submitting this pull request, I confirm that my contribution is under the terms of the Apache 2.0 and PostgreSQL licenses, and grant any person obtaining a copy of the contribution permission to relicense all or a portion of my contribution to the PostgreSQL License solely to contribute all or a portion of my contribution to the PostgreSQL open source project.

For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/babelfish-for-postgresql/babelfish_extensions/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Review by nasbyj — CHANGES_REQUESTED** [review]
Can you add at least a minimal test of a non-PGXS build? Or maybe that's already happening elsewhere?

**Comment by nasbyj** [comment]
(FYI, I edited the title and description of this PR)

**Comment by 3manuek** [comment]
> (FYI, I edited the title and description of this PR)

@nasbyj I don't see your title edition, but I set it to the same name as the original issue #76 .

> Can you add at least a minimal test of a non-PGXS build? Or maybe that's already happening elsewhere?

Yes, this should be happening in a new repository for testing the distribution. Probably I can extend this patch with some documentation.

**Comment by 3manuek** [comment]
> Can you add at least a minimal test of a non-PGXS build? Or maybe that's already happening elsewhere?

What we can do, is to create a branch from engine tags, attach the extensions, do the changes that we have done in the plain distributions and let the CI run the test. But I'm not seeing this possible in this repository. cc/ @nasbyj

**Comment by wieck** [comment]
These changes are insufficient. Some Makefiles depend on finding the correct (just compiled but not yet installed) pg_config executable and/or the current source tree. The latter isn't much of a problem, but the former basically require to run `make install` before running `make -C contrib/babelfishpg_NAME`.

We need to get rid of the need for environment variables PG_CONFIG and PG_SRC to be set.

**Comment by 3manuek** [comment]
> These changes are insufficient. Some Makefiles depend on finding the correct (just compiled but not yet installed) pg_config executable and/or the current source tree. The latter isn't much of a problem, but the former basically require to run `make install` before running `make -C contrib/babelfishpg_NAME`.
> 
> We need to get rid of the need for environment variables PG_CONFIG and PG_SRC to be set.

I'm aware of this, but I just needed the basics to make it work under the engine code. We can do more lean work here, but my idea was just to allow to compile for make the tarball distributions work. Within this change, we can still set up the PG_CONFIG and PG_SRC variables and do the compilation just by fetching the code through git-archive and prefix (that is, without modifying the extensions code).

But I agree definitively that extensions should deal with this eventually. What are your thoughts @nasbyj  @kuntalghosh @hsuamz ? Should we consider the effort to get a leaner code for compilation in the distribution? IMHO it would be a huge win.

**Pull request closed without merging**
